component:
  template:
    tfvars:
      s3_bucket_name: 'www-stage.mitocgroup.com'
      s3_bucket_region: 'us-west-1'

build:
  env:
    variables:
      THUB_ENV: 'test'
      THUB_S3_PATH: 's3://www-stage.mitocgroup.com'
      THUB_MAX_AGE: '604800'
