## local config
component:
  name: 's3_bucket'
  mapping:
    - '.'

## build config
build:
  env:
    variables:
      THUB_ENV: "dev"
      THUB_INDEX_FILE: "index.txt"
      THUB_S3_PATH: "s3://www-dev.mitocgroup.com"
      THUB_ROBOTS: "../../robots.txt"
      THUB_BUILD_PATH: "../../build"
      THUB_SOURCE_PATH: "../../assets ../../static/fonts ../../static/images ../../views"
      THUB_BUILD_OK: "false"
      THUB_MAX_AGE: "600"
  phases:
    pre_build:
      commands:
        - echo "BUILD: Running pre_build step"
        - ./scripts/download.sh $THUB_INDEX_FILE $THUB_S3_PATH/$THUB_INDEX_FILE
        - ./scripts/compare.sh $THUB_INDEX_FILE $THUB_SOURCE_PATH
      finally:
        - echo "BUILD: pre_build step successful"
    build:
      commands:
        - echo "BUILD: Running build step"
        - ../../bin/compile.sh
      finally:
        - echo "BUILD: build step successful"
    post_build:
      commands:
        - echo "BUILD: Running post_build step"
        - ./scripts/shasum.sh $THUB_BUILD_PATH/$THUB_INDEX_FILE
        - ./scripts/upload.sh $THUB_BUILD_PATH $THUB_S3_PATH --cache-control max-age=$THUB_MAX_AGE
        - rm -f .terrahub_build.env $THUB_INDEX_FILE
      finally:
        - echo "BUILD: post_build step successful"
