component:
  template:
    tfvars:
      s3_bucket_name: 'www-test.mitocgroup.com'
      s3_bucket_region: 'us-west-2'
build:
  env:
    variables:
      THUB_ENV: 'test'
      THUB_S3_PATH: 's3://www-test.mitocgroup.com'
      THUB_MAX_AGE: '600'
