---
$:
  preprocess:
    '$.e2e.wait.uri.0': 'eval'
    '$.cache.options.1.region': 'eval'
    '$.cache.options.1.accessKeyId': 'eval'
    '$.cache.options.1.secretAccessKey': 'eval'
  npm:
    scripts: []
  emit:
    pattern:
      - /.+\.js$/i
    ignore:
      - /^(.*\/)?bin(\/?$)?/i
      - /^(.*\/)?node_modules(\/?$)?/i
  test:
    mocha:
      options:
        ui: 'bdd'
        reporter: 'spec'
    pattern:
      - /.+\.spec\.js$/i
    ignore: ~
  cache:
    driver: 's3'
    options:
      - 's3://travis-metadata/cache/MitocGroup/www'
      -
        region: 'process.env.AWS_DEFAULT_REGION'
        accessKeyId: 'process.env.AWS_ACCESS_KEY_ID'
        secretAccessKey: 'process.env.AWS_SECRET_ACCESS_KEY'  
  e2e:
    pattern:
      - /.+\.e2e\.js$/i
    ignore: []
    browsers: 
      - puppeteer
    wait:
      interval: 500
      timeout: 60000
      uri:
        - 'process.env.DEPLOY_HOST'

test-suite:
  root: 'test'
  dependencies:
    chance: 'latest'  
