project:
  name: MitocGroup_Website
  code: eee23249
  include:
    - terraform
  exclude:
    - .git
    - .terraform
    - node_modules
template:
  locals:
    region: us-east-1
    account_id: 123456789000
  terraform:
    backend:
      s3:
        region: us-east-1
        bucket: data-lake-mitocgroup-us-east-1
        key: 'terraform/mitocgroup/www/${tfvar.terrahub["component"]["name"]}/terraform.tfstate'
        workspace_key_prefix: terraform_workspaces
  provider:
    aws:
      region: local.region
      allowed_account_ids:
        - local.account_id
terraform:
  varFile:
    - default.tfvars
  version: 0.12.23
