## project config
project:
  name: 'MitocGroup_Website'
  code: 'eee23249'
  include: ['.terrahub']
  exclude: ['**/node_modules/**','**/.terraform/**','**/.git/**']

## terrahub template
template:
  locals:
    region: 'us-east-1'
    account_id: '123456789012'
  terraform:
    backend:
      s3:
        bucket: 'data-lake-mitocgroup-us-east-1'
        region: 'us-east-1'
        workspace_key_prefix: 'terraform_workspaces'
  provider:
    aws:
      region: '${local.region}'
      allowed_account_ids: ['${local.account_id}']

## terraform config
terraform:
  varFile: ['default.tfvars']
