component:
  template:
    tfvars:
      default_tags:
        Description: Managed by TerraHub
        Name: MitocGroupStageLambdaImageHandlereee23249
        ThubCode: eee23249
        ThubEnv: stage
      lambda_function_name: MitocGroupStageLambdaImageHandlereee23249
      lambda_env_var_source_buckets: www-stage.mitocgroup.com
