component:
  name: api_gateway_domain_name
  dependsOn:
    - api_gateway_rest_api
  mapping:
    - ../api_gateway_rest_api
  template:
    data:
      aws_acm_certificate:
        acm_certificate:
          domain: var.acm_certificate_domain_name
    resource:
      aws_api_gateway_domain_name:
        api_gateway_domain_name:
          count: 'contains(list("test"), terraform.workspace) ? 0 : 1'
          domain_name: var.api_gateway_domain_name
          endpoint_configuration:
            - types: var.api_gateway_domain_name_endpoint_type
          regional_certificate_arn: data.aws_acm_certificate.acm_certificate.arn
    output:
      id:
        value: aws_api_gateway_domain_name.api_gateway_domain_name.*.id
      regional_zone_id:
        value: aws_api_gateway_domain_name.api_gateway_domain_name.*.regional_zone_id
      regional_domain_name:
        value: >-
          aws_api_gateway_domain_name.api_gateway_domain_name.*.regional_domain_name
    tfvars:
      acm_certificate_domain_name: mitocgroup.com
      api_gateway_domain_name: api-dev.mitocgroup.com
      api_gateway_domain_name_endpoint_type:
        - REGIONAL
