component:
  name: iam_api_exec_access
  template:
    data:
      template_file:
        iam_role_policy:
          template: >-
            file(format("%s/%s", local.component["path"],
            var.iam_role_policy_template_path))
          vars:
            region: local.region
            account_id: local.account_id
            iam_role_policy_resources_01: var.iam_role_policy_resources_01
        iam_trust_policy:
          template: >-
            file(format("%s/%s", local.component["path"],
            var.iam_trust_policy_template_path))
    resource:
      aws_iam_role:
        iam_api_exec_access:
          count: 'contains(list("test"), terraform.workspace) ? 0 : 1'
          assume_role_policy: data.template_file.iam_trust_policy.rendered
          description: var.iam_role_description
          force_detach_policies: var.iam_role_force_detach_policies
          name: var.iam_role_name
          path: var.iam_role_path
      aws_iam_role_policy:
        iam_api_exec_access:
          count: 'contains(list("test"), terraform.workspace) ? 0 : 1'
          name: var.iam_role_policy_name
          policy: data.template_file.iam_role_policy.rendered
          role: 'element(aws_iam_role.iam_api_exec_access.*.id, count.index)'
    output:
      arn:
        value: aws_iam_role.iam_api_exec_access.*.arn
      create_date:
        value: aws_iam_role.iam_api_exec_access.*.create_date
      unique_id:
        value: aws_iam_role.iam_api_exec_access.*.unique_id
      name:
        value: aws_iam_role.iam_api_exec_access.*.name
      description:
        value: aws_iam_role.iam_api_exec_access.*.description
    tfvars:
      iam_role_name: MitocGroupDevApiExecAccesseee23249
      iam_role_policy_name: MitocGroupDevApiExecAccessCustomeee23249
      iam_role_description: Managed by TerraHub
      iam_role_path: /
      iam_role_force_detach_policies: false
      iam_role_policy_resources_01: '*MitocGroupDev*'
      iam_role_policy_template_path: ./policies/api_exec_access_role_policy.json.tpl
      iam_trust_policy_template_path: ./policies/api_exec_access_trust_policy.json.tpl
