component:
  name: api_gateway_base_path_mapping
  dependsOn:
    - api_gateway_domain_name
    - api_gateway_rest_api
  mapping:
    - ../api_gateway_rest_api
  template:
    resource:
      aws_api_gateway_base_path_mapping:
        api_gateway_base_path_mapping:
          count: 'contains(list("test"), terraform.workspace) ? 0 : 1'
          api_id: >-
            element(data.terraform_remote_state.api_gateway_rest_api.outputs.thub_id,
            count.index)
          base_path: var.api_gateway_base_path_mapping_base_path
          domain_name: var.api_gateway_domain_name
          stage_name: var.api_gateway_deployment_stage_name
    dynamic:
      data:
        terraform_remote_state:
          - component: api_gateway_rest_api
            name: api_gateway_rest_api
    output:
      domain_name:
        value: >-
          aws_api_gateway_base_path_mapping.api_gateway_base_path_mapping.*.domain_name
    tfvars:
      api_gateway_deployment_stage_name: ''
      api_gateway_base_path_mapping_base_path: ''
      api_gateway_domain_name: api-dev.mitocgroup.com
