component:
  name: iam_lambda_image_handler
  template:
    data:
      template_file:
        iam_role_policy:
          template: >-
            file(format("%s/%s", local.component["path"],
            var.iam_role_policy_template_path))
          vars:
            region: local.region
            account_id: local.account_id
        iam_trust_policy:
          template: >-
            file(format("%s/%s", local.component["path"],
            var.iam_trust_policy_template_path))
    resource:
      aws_iam_role:
        iam_lambda_image_handler:
          count: 'contains(list("test"), terraform.workspace) ? 0 : 1'
          assume_role_policy: data.template_file.iam_trust_policy.rendered
          description: Managed by TerraHub
          force_detach_policies: 'false'
          name: var.iam_role_name
          path: var.iam_role_path
      aws_iam_role_policy:
        iam_lambda_image_handler:
          count: 'contains(list("test"), terraform.workspace) ? 0 : 1'
          name: var.iam_role_policy_name
          policy: data.template_file.iam_role_policy.rendered
          role: 'element(aws_iam_role.iam_lambda_image_handler.*.id, count.index)'
    output:
      arn:
        value: aws_iam_role.iam_lambda_image_handler.*.arn
      create_date:
        value: aws_iam_role.iam_lambda_image_handler.*.create_date
      unique_id:
        value: aws_iam_role.iam_lambda_image_handler.*.unique_id
      name:
        value: aws_iam_role.iam_lambda_image_handler.*.name
      description:
        value: aws_iam_role.iam_lambda_image_handler.*.description
    tfvars:
      iam_role_name: MitocGroupDevImageHandlerLambdaExeceee23249
      iam_role_policy_name: MitocGroupDevImageHandlerLambdaExecCustomeee23249
      iam_role_path: /
      iam_role_force_detach_policies: false
      iam_role_policy_template_path: ./policies/lambda_image_handler_role_policy.json.tpl
      iam_trust_policy_template_path: ./policies/lambda_image_handler_trust_policy.json.tpl
