component:
  template:
    locals:
      region: us-east-2
    tfvars:
      s3_bucket_name: 'www.mitocgroup.com'
      s3_bucket_region: 'us-east-2'
build:
  env:
    variables:
      THUB_ENV: 'master'
      THUB_S3_PATH: 's3://www.mitocgroup.com'
      THUB_ROBOTS: '../../robots-prod.txt'
      THUB_SITEMAP: '../../sitemap.xml'
      THUB_MAX_AGE: '31536000'
