component:
  template:
    tfvars:
      aliases:
        - www-test.mitocgroup.com
      comment: www-test.mitocgroup.com
build:
  env:
    variables:
      THUB_S3_BUCKET_NAME: www-test.mitocgroup.com
