component:
  template:
    tfvars:
      aliases:
        - www-stage.mitocgroup.com
      comment: www-stage.mitocgroup.com
build:
  env:
    variables:
      THUB_S3_BUCKET_NAME: www-stage.mitocgroup.com
