component:
  template:
    tfvars:
      aliases:
        - www.mitocgroup.com
      comment: www.mitocgroup.com
      min_ttl: 86400
      default_ttl: 31536000
build:
  env:
    variables:
      THUB_S3_BUCKET_NAME: www.mitocgroup.com
